-- ==============================================================================
-- Engage-kit Database Integrated Schema
-- ==============================================================================
-- このファイルは、Engage-kitのデータベース環境を構築するための統合スクリプトです。
-- 以下の機能を含みます：
-- 1. 拡張機能有効化
-- 2. テーブル定義 (projects, analytics_logs, leads)
-- 3. セキュリティ設定 (RLS: Row Level Security)
-- 4. ストレージバケット設定
-- 5. 集計用ビュー (Dashboard用)
-- 6. RPC関数
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. 拡張機能
-- ------------------------------------------------------------------------------
create extension if not exists "uuid-ossp";

-- ------------------------------------------------------------------------------
-- 2. テーブル定義
-- ------------------------------------------------------------------------------

-- Projects テーブル
create table if not exists projects (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users, -- 匿名・未ログイン対応のためNULL許容
  title text default 'Untitled Project',
  data jsonb default '{}'::jsonb,              -- エディタ編集用データ
  published_content jsonb,                     -- 公開用（ビルド済み）データ
  is_published boolean default false,
  published_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Analytics Logs (アクセスログ)
create table if not exists analytics_logs (
  id bigint generated by default as identity primary key,
  project_id uuid references projects(id) on delete cascade not null,
  session_id text not null,
  event_type text not null, -- 'page_view', 'click', 'node_execution' 等
  node_id text,
  node_type text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Leads (フォーム回答データ)
create table if not exists leads (
  id uuid default uuid_generate_v4() primary key,
  project_id uuid references projects(id) on delete cascade not null,
  session_id text not null, 
  data jsonb not null default '{}'::jsonb,
  ip_address text,
  user_agent text,
  referrer text,
  device_type text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- ------------------------------------------------------------------------------
-- 3. ストレージ設定
-- ------------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('project-assets', 'project-assets', true)
on conflict (id) do nothing;

-- ------------------------------------------------------------------------------
-- 4. セキュリティ設定 (RLS)
-- ------------------------------------------------------------------------------

-- ■ Projects Table
alter table projects enable row level security;

drop policy if exists "Users can view own projects" on projects;
drop policy if exists "Users can insert own projects" on projects;
drop policy if exists "Users can update own projects" on projects;
drop policy if exists "Users can delete own projects" on projects;
drop policy if exists "Public can view published projects" on projects;
drop policy if exists "Public can insert projects" on projects;
drop policy if exists "Public can update projects" on projects;
drop policy if exists "Public can delete projects" on projects;

-- 誰でもプロジェクト作成可能 (匿名ユーザー対応)
create policy "Public can insert projects" on projects for insert with check (true);
-- 誰でも更新可能 (実運用では所有権チェック推奨だが、現状の仕様に合わせて開放)
create policy "Public can update projects" on projects for update using (true);
-- 誰でも削除可能 (開発環境用の暫定対応)
create policy "Public can delete projects" on projects for delete using (true);
-- 自分のプロジェクトは見れる
create policy "Users can view own projects" on projects for select using (auth.uid() = user_id);
-- 公開プロジェクトは誰でも見れる (Viewer用)
create policy "Public can view published projects" on projects for select using (true);


-- ■ Analytics Logs Table
alter table analytics_logs enable row level security;

drop policy if exists "Public can insert analytics logs" on analytics_logs;
drop policy if exists "Users can view analytics for own projects" on analytics_logs;
drop policy if exists "Public can view analytics logs" on analytics_logs;

-- Viewerからのログ送信を許可 (誰でもInsert可)
create policy "Public can insert analytics logs" on analytics_logs for insert with check (true);

-- ログの閲覧: 所有者 + 匿名ユーザー(現状の仕様に合わせて開放)
-- create policy "Users can view analytics for own projects" on analytics_logs for select using (project_id in (select id from projects where user_id = auth.uid()));
create policy "Public can view analytics logs" on analytics_logs for select using (true);


-- ■ Leads Table
alter table leads enable row level security;

drop policy if exists "Public can insert leads" on leads;
drop policy if exists "Users can view own leads" on leads;
drop policy if exists "Public can view leads" on leads;
drop policy if exists "Public can delete leads" on leads;

-- サイト訪問者がデータを送信できるようにする
create policy "Public can insert leads" on leads for insert with check (true);

-- データの閲覧・削除: 所有者 + 匿名ユーザー(現状の仕様に合わせて開放)
create policy "Public can view leads" on leads for select using (true);
create policy "Public can delete leads" on leads for delete using (true);


-- ■ Storage Policies
drop policy if exists "Public Access" on storage.objects;
drop policy if exists "Authenticated users can upload" on storage.objects;
drop policy if exists "Authenticated users can update own files" on storage.objects;
drop policy if exists "Authenticated users can delete own files" on storage.objects;

-- 閲覧は誰でもOK
create policy "Public Access" on storage.objects for select using ( bucket_id = 'project-assets' );
-- アップロードは認証済み(匿名含む)のみ
create policy "Authenticated users can upload" on storage.objects for insert with check (
  bucket_id = 'project-assets' and auth.role() = 'authenticated'
);
-- 更新・削除は所有者のみ
create policy "Authenticated users can update own files" on storage.objects for update using (
  bucket_id = 'project-assets' and auth.uid() = owner
);
create policy "Authenticated users can delete own files" on storage.objects for delete using (
  bucket_id = 'project-assets' and auth.uid() = owner
);


-- ------------------------------------------------------------------------------
-- 5. Analytics Views (集計ビュー)
-- ------------------------------------------------------------------------------
-- ダッシュボード表示用の集計ビューを作成します。
-- ※これらのビューがないとダッシュボードに数字が表示されません。

-- (1) 日次統計 (PV, UU, CV, CVR)
drop view if exists analytics_daily_stats cascade;
create or replace view analytics_daily_stats as
with daily_pv as (
  select
    project_id,
    date_trunc('day', created_at) as date,
    count(*) as pv,
    count(distinct session_id) as uu
  from analytics_logs
  where event_type = 'page_view'
  group by project_id, date_trunc('day', created_at)
),
daily_cv as (
  select
    project_id,
    date_trunc('day', created_at) as date,
    count(*) as cv
  from leads
  group by project_id, date_trunc('day', created_at)
)
select
  coalesce(pv.project_id, cv.project_id) as project_id,
  coalesce(pv.date, cv.date) as date,
  coalesce(pv.pv, 0) as pv,
  coalesce(pv.uu, 0) as uu,
  coalesce(cv.cv, 0) as cv,
  case
    when coalesce(pv.pv, 0) > 0 then (coalesce(cv.cv, 0)::float / pv.pv::float) * 100
    else 0
  end as cvr
from daily_pv pv
full outer join daily_cv cv on pv.project_id = cv.project_id and pv.date = cv.date;


-- (2) ノード別統計
drop view if exists analytics_node_stats cascade;
create or replace view analytics_node_stats as
select
  project_id,
  node_id,
  count(*) as interaction_count,
  count(distinct session_id) as unique_users
from analytics_logs
where node_id is not null
group by project_id, node_id;


-- (3) A/Bテスト統計
drop view if exists analytics_ab_test_stats cascade;
create or replace view analytics_ab_test_stats as
select
  l.project_id,
  l.metadata->>'variant' as variant,
  count(*) as visitors,
  0 as conversions, -- 現状はプレースホルダー
  0 as conversion_rate
from analytics_logs l
where l.event_type = 'ab_test_assignment'
group by l.project_id, l.metadata->>'variant';

-- Viewへのアクセス権限
grant select on analytics_daily_stats to authenticated, anon;
grant select on analytics_node_stats to authenticated, anon;
grant select on analytics_ab_test_stats to authenticated, anon;


-- ------------------------------------------------------------------------------
-- 6. Functions (RPC)
-- ------------------------------------------------------------------------------

-- 月間回答数制限チェック関数
drop function if exists check_monthly_lead_limit;
create or replace function check_monthly_lead_limit(project_uuid uuid)
returns boolean
language plpgsql
security definer
as $$
declare
  current_count int;
  limit_count int := 100;
begin
  select count(*)
  into current_count
  from leads
  where project_id = project_uuid
  and date_trunc('month', created_at) = date_trunc('month', now());

  return current_count < limit_count;
end;
$$;
