-- ==============================================================================
-- 0. 事前準備 (テーブル作成)
-- ==============================================================================

-- Projects テーブルが存在しない場合の安全策 (念のため)
create table if not exists projects (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users not null,
  title text default 'Untitled Project',
  content jsonb default '{}'::jsonb,
  is_published boolean default false,
  published_content jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 【修正箇所】Analytics Logs テーブルを作成 (これが抜けていました)
create table if not exists analytics_logs (
  id bigint generated by default as identity primary key,
  project_id uuid references projects(id) on delete cascade not null,
  session_id text not null,
  event_type text not null, -- 'view', 'node_execution', etc.
  node_id text,
  node_type text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Leads テーブルの作成
create table if not exists leads (
  id uuid default uuid_generate_v4() primary key,
  project_id uuid not null references projects(id) on delete cascade,
  session_id text not null, 
  data jsonb not null default '{}'::jsonb,
  ip_address text,
  user_agent text,
  referrer text,
  device_type text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);


-- ==============================================================================
-- 1. Enable Row Level Security (RLS) on Tables
-- ==============================================================================

-- Projects Table
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- 既存のポリシーがある場合のエラーを防ぐため、一度削除してから再作成
DROP POLICY IF EXISTS "Users can view own projects" ON projects;
DROP POLICY IF EXISTS "Users can insert own projects" ON projects;
DROP POLICY IF EXISTS "Users can update own projects" ON projects;
DROP POLICY IF EXISTS "Users can delete own projects" ON projects;
DROP POLICY IF EXISTS "Public can view projects" ON projects;

CREATE POLICY "Users can view own projects" ON projects FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own projects" ON projects FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own projects" ON projects FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own projects" ON projects FOR DELETE USING (auth.uid() = user_id);

-- Viewer用に公開プロジェクトは誰でも見れるようにする (is_published カラムがあればそれを使う)
CREATE POLICY "Public can view projects" ON projects FOR SELECT USING (true);


-- Analytics Logs Table
ALTER TABLE analytics_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can insert analytics logs" ON analytics_logs;
DROP POLICY IF EXISTS "Users can view analytics for own projects" ON analytics_logs;

-- Viewerからのログ送信を許可 (誰でもInsert可)
CREATE POLICY "Public can insert analytics logs" ON analytics_logs FOR INSERT WITH CHECK (true);

-- オーナーのみログ閲覧可
CREATE POLICY "Users can view analytics for own projects" ON analytics_logs FOR SELECT USING (
  project_id IN (SELECT id FROM projects WHERE user_id = auth.uid())
);


-- Leads Table
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert leads" ON leads;
DROP POLICY IF EXISTS "Allow project owner view leads" ON leads;
DROP POLICY IF EXISTS "Allow project owner delete leads" ON leads;

-- サイト訪問者がデータを送信できるようにする
CREATE POLICY "Allow public insert leads" ON leads FOR INSERT TO public WITH CHECK (true);

-- プロジェクト所有者のみ閲覧可能
CREATE POLICY "Allow project owner view leads" ON leads FOR SELECT TO authenticated USING (
  project_id IN (SELECT id FROM projects WHERE user_id = auth.uid())
);

-- データの削除を許可
CREATE POLICY "Allow project owner delete leads" ON leads FOR DELETE TO authenticated USING (
  project_id IN (SELECT id FROM projects WHERE user_id = auth.uid())
);


-- ==============================================================================
-- 2. Storage Bucket Setup
-- ==============================================================================

-- Create a new storage bucket for project assets
INSERT INTO storage.buckets (id, name, public)
VALUES ('project-assets', 'project-assets', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can update own files" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can delete own files" ON storage.objects;

-- Public Read
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'project-assets' );

-- Authenticated Upload
CREATE POLICY "Authenticated users can upload" ON storage.objects FOR INSERT WITH CHECK (
  bucket_id = 'project-assets' AND auth.role() = 'authenticated'
);

-- Authenticated Update
CREATE POLICY "Authenticated users can update own files" ON storage.objects FOR UPDATE USING (
  bucket_id = 'project-assets' AND auth.uid() = owner
);

-- Authenticated Delete
CREATE POLICY "Authenticated users can delete own files" ON storage.objects FOR DELETE USING (
  bucket_id = 'project-assets' AND auth.uid() = owner
);